-- Auto-generated from schema-map-postgres.yaml (map@74ce4f4)
-- engine: postgres
-- table:  kms_keys

CREATE TABLE IF NOT EXISTS kms_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id BIGINT NOT NULL,
  external_key_ref VARCHAR(512) NOT NULL,
  purpose TEXT NOT NULL DEFAULT 'wrap',
  algorithm VARCHAR(64) NULL,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_kms_purpose CHECK (purpose IN ('wrap','encrypt','both')),
  CONSTRAINT chk_kms_status  CHECK (status  IN ('active','retired','disabled'))
);
